name: Format

on:
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
        with:
          configFile: .commitlintrc.json
          helpURL: https://github.com/luckyjiet/opencoin-frontend
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run prettier
        run: npm run format:check
